name: JSON Check

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  syntax_check:
    name: JSON Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: JSON Syntax Check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: '\\.json$'
