name: JSON Check

on:
  pull_request:

jobs:
  syntax_check:
    name: JSON Syntax Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JSON Syntax Check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: '\\.json$'
